#! /bin/bash

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

setup_f2fs() {
    ZNS=$1
    MOUNT="/mnt/f2fs"

    DEV=$(sudo ../nullblk_create 4096 4096)
    export DEV
    export ZNS

    sudo nvme zns reset-zone /dev/${ZNS} -a
    echo mq-deadline | sudo tee /sys/block/${ZNS}/queue/scheduler > /dev/null
    sudo env "PATH=${PATH}" mkfs.f2fs -f -m -c /dev/${ZNS} /dev/${DEV}
    sudo mkdir -p /mnt/f2fs
    sudo mount -t f2fs /dev/${DEV} ${MOUNT}
    sudo chown -R ${USER} /mnt/f2fs
}

cleanup() {
    sudo sync # avoid errors on busy unmount
    sudo umount /dev/${DEV}
    DEV_ID=$(echo "${DEV: -1}")
    sudo ../nullblk_delete $DEV_ID
}

ZNS=$1
export ZNS

DIR=data-f2fs

mkdir -p ${DIR}

echo "Running benchmark with 1 hot file"
setup_f2fs ${ZNS}
sudo env "NR_FILES=2" ${FIO_HOME}/fio --output-format=json --output=${DIR}/single_file.json job.fio
cleanup

echo "Running benchmark with 2 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=2" ${FIO_HOME}/fio --output-format=json --output=${DIR}/two_file.json job.fio
cleanup

echo "Running benchmark with 3 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=3" ${FIO_HOME}/fio --output-format=json --output=${DIR}/three_file.json job.fio
cleanup

echo "Running benchmark with 4 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=4" ${FIO_HOME}/fio --output-format=json --output=${DIR}/four_file.json job.fio
cleanup

echo "Running benchmark with 5 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=5" ${FIO_HOME}/fio --output-format=json --output=${DIR}/five_file.json job.fio
cleanup

echo "Running benchmark with 6 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=6" ${FIO_HOME}/fio --output-format=json --output=${DIR}/six_file.json job.fio
cleanup

echo "Running benchmark with 7 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=7" ${FIO_HOME}/fio --output-format=json --output=${DIR}/seven_file.json job.fio
cleanup

echo "Running benchmark with 8 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=8" ${FIO_HOME}/fio --output-format=json --output=${DIR}/eight_file.json job.fio
cleanup

echo "Running benchmark with 9 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=9" ${FIO_HOME}/fio --output-format=json --output=${DIR}/nine_file.json job.fio
cleanup

echo "Running benchmark with 10 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=10" ${FIO_HOME}/fio --output-format=json --output=${DIR}/ten_file.json job.fio
cleanup

echo "Running benchmark with 11 hot files"
setup_f2fs ${ZNS}
sudo env "NR_FILES=11" ${FIO_HOME}/fio --output-format=json --output=${DIR}/eleven_file.json job.fio
cleanup
