#! /bin/bash

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

setup_msf2fs() {
    ZNS=$1
    MOUNT="/mnt/f2fs"

    DEV=$(sudo ../nullblk_create 4096 4096)
    export DEV
    export ZNS

    sudo nvme zns reset-zone /dev/${ZNS} -a
    echo mq-deadline | sudo tee /sys/block/${ZNS}/queue/scheduler > /dev/null
    sudo env "PATH=${PATH}" mkfs.f2fs -f -m -c /dev/${ZNS} /dev/${DEV}
    sudo mkdir -p /mnt/f2fs
    sudo mount -t f2fs -o hot_data_streams=$2 -o warm_data_streams=$3 -o cold_data_streams=$4 -o stream_policy=$5 /dev/${DEV} ${MOUNT}
    sudo chown -R ${USER} /mnt/f2fs
}

cleanup() {
    sudo sync # avoid errors on busy unmount
    sudo umount /dev/${DEV}
    DEV_ID=$(echo "${DEV: -1}")
    sudo ../nullblk_delete $DEV_ID
}

ZNS=$1
export ZNS

POLICIES=("spf" "srr")

for policy in ${POLICIES[@]}; do

    DIR=data-${policy}

    mkdir -p ${DIR}

    echo "Running benchmark with 1 stream and 1 hot file and policy ${policy}"
    setup_msf2fs ${ZNS} 1 1 1 ${policy}
    sudo env "JOBS=1" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-1.json job.fio
    cleanup

    echo "Running benchmark with 2 streams and 2 hot files and ${policy}"
    setup_msf2fs ${ZNS} 2 1 1 ${policy}
    sudo env "JOBS=2" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-2.json job.fio
    cleanup

    echo "Running benchmark with 3 streams and 3 hot files and ${policy}"
    setup_msf2fs ${ZNS} 3 1 1 ${policy}
    sudo env "JOBS=3" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-3.json job.fio
    cleanup

    echo "Running benchmark with 4 streams and 4 hot files and ${policy}"
    setup_msf2fs ${ZNS} 4 1 1 ${policy}
    sudo env "JOBS=4" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-4.json job.fio
    cleanup

    echo "Running benchmark with 5 streams and 5 hot files and ${policy}"
    setup_msf2fs ${ZNS} 5 1 1 ${policy}
    sudo env "JOBS=5" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-5.json job.fio
    cleanup

    echo "Running benchmark with 6 streams and 6 hot files and ${policy}"
    setup_msf2fs ${ZNS} 6 1 1 ${policy}
    sudo env "JOBS=6" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-6.json job.fio
    cleanup

    echo "Running benchmark with 7 streams and 7 hot files and ${policy}"
    setup_msf2fs ${ZNS} 7 1 1 ${policy}
    sudo env "JOBS=7" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-7.json job.fio
    cleanup

    echo "Running benchmark with 8 streams and 8 hot files and ${policy}"
    setup_msf2fs ${ZNS} 8 1 1 ${policy}
    sudo env "JOBS=8" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-8.json job.fio
    cleanup

    echo "Running benchmark with 9 streams and 9 hot files and ${policy}"
    setup_msf2fs ${ZNS} 9 1 1 ${policy}
    sudo env "JOBS=9" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-9.json job.fio
    cleanup

    echo "Running benchmark with 10 streams and 10 hot files and ${policy}"
    setup_msf2fs ${ZNS} 10 1 1 ${policy}
    sudo env "JOBS=10" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-10.json job.fio
    cleanup

    echo "Running benchmark with 11 streams and 11 hot files and ${policy}"
    setup_msf2fs ${ZNS} 11 1 1 ${policy}
    sudo env "JOBS=11" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-11.json job.fio
    cleanup
done
