#! /bin/bash

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

setup_f2fs() {
    ZNS=$1
    MOUNT="/mnt/f2fs"

    DEV=$(sudo ../nullblk_create 4096 4096)
    export DEV
    export ZNS

    sudo nvme zns reset-zone /dev/${ZNS} -a
    echo mq-deadline | sudo tee /sys/block/${ZNS}/queue/scheduler > /dev/null
    sudo env "PATH=${PATH}" mkfs.f2fs -f -m -c /dev/${ZNS} /dev/${DEV}
    sudo mkdir -p /mnt/f2fs
    sudo mount -t f2fs /dev/${DEV} ${MOUNT}
    sudo chown -R ${USER} /mnt/f2fs
}

cleanup() {
    sudo sync # avoid errors on busy unmount
    sudo umount /dev/${DEV}
    DEV_ID=$(echo "${DEV: -1}")
    sudo ../nullblk_delete $DEV_ID
}

ZNS=$1

DIR=data-f2fs
mkdir -p ${DIR}

echo "Running benchmark with 1 hot file"
setup_f2fs ${ZNS}
sudo env "JOBS=1" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-1.json job.fio
cleanup

echo "Running benchmark with 2 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=2" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-2.json job.fio
cleanup

echo "Running benchmark with 3 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=3" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-3.json job.fio
cleanup

echo "Running benchmark with 4 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=4" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-4.json job.fio
cleanup

echo "Running benchmark with 5 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=5" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-5.json job.fio
cleanup

echo "Running benchmark with 6 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=6" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-6.json job.fio
cleanup

echo "Running benchmark with 7 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=7" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-7.json job.fio
cleanup

echo "Running benchmark with 8 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=8" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-8.json job.fio
cleanup

echo "Running benchmark with 9 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=9" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-9.json job.fio
cleanup

echo "Running benchmark with 10 hot files"
setup_f2fs ${ZNS}
sudo env "JOBS=10" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-10.json job.fio
cleanup

echo "Running benchmark with 11 hot files"
setup_f2fs ${ZNS} 
sudo env "JOBS=11" ${FIO_HOME}/fio --output-format=json --output=${DIR}/files-11.json job.fio
cleanup
