#! /bin/bash

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

ZNS=$1

export ZNS

setup_f2fs() {
    MOUNT="/mnt/f2fs"

    DEV=$(sudo ../nullblk_create 4096 4096)
    export DEV
    export ZNS

    sudo nvme zns reset-zone /dev/${ZNS} -a
    echo mq-deadline | sudo tee /sys/block/${ZNS}/queue/scheduler > /dev/null
    sudo env "PATH=${PATH}" mkfs.f2fs -f -m -c /dev/${ZNS} /dev/${DEV}
    sudo mkdir -p /mnt/f2fs
    sudo mount -t f2fs /dev/${DEV} ${MOUNT}
    sudo chown -R ${USER} /mnt/f2fs
}

cleanup() {
    sudo sync # avoid errors on busy unmount
    sudo umount /dev/${DEV}
    DEV_ID=$(echo "${DEV: -1}")
    sudo ../nullblk_delete $DEV_ID
}

DATA="data"

mkdir -p ${DATA}

JOBS=(1 2 3 4 5)

for jobs in ${JOBS[@]}; do
    echo "Running benchmark with hot file - jobs ${jobs}"
    setup_f2fs
    sudo env "JOBS=${jobs}" ${FIO_HOME}/fio --output-format=json --output=${DATA}/single_stream-${jobs}.json jobs/f2fs_single_stream.fio
    cleanup

    echo "Running benchmark with hot and cold files - jobs ${jobs}"
    setup_f2fs
    sudo env "JOBS=${jobs}" ${FIO_HOME}/fio --output-format=json --output=${DATA}/two_stream-${jobs}.json jobs/f2fs_two_stream.fio
    cleanup

    echo "Running benchmark with hot warm and cold files - jobs ${jobs}"
    setup_f2fs
    sudo env "JOBS=${jobs}" ${FIO_HOME}/fio --output-format=json --output=${DATA}/three_stream-${jobs}.json jobs/f2fs_three_stream.fio
    cleanup
done
