#! /bin/bash

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

ZNS=$1
export ZNS

POLICIES=("spf" "srr")

for policy in ${POLICIES[@]}; do

    DIR=data-${ZNS}-${policy}-$(date +"%Y_%m_%d_%I_%M_%p")

    mkdir -p ${DIR}
    export DIR
    export policy

    ./f2fs_stream_bench
done
