#! /bin/bash

set -e

if [ $# != 1 ]; then
    echo "Usage: $0 <ZNS device (e.g., nvme0n2)>"
    exit 1
fi

DEV=$1
IODEPTH=(1 2 4 8 16 32 64 128)
ZONES=(1 2 3 4 5 6)
NAMES=("zns-single_zone" "zns-two_zone" "zns-three_zone" "zns-four_zone" "zns-five_zone" "zns-six_zone")

echo mq-deadline | sudo tee /sys/block/${DEV}/queue/scheduler > /dev/null

for zones in ${ZONES[@]}; do

    DATA_DIR="data/${NAMES[zones - 1]}_iodepth"
    mkdir -p $DATA_DIR

    for iodepth in ${IODEPTH[@]}; do
        echo "Running benchmark with ${zones} zones iodepth: ${iodepth}"
        sudo nvme zns reset-zone -a /dev/${DEV}

        sudo ${FIO_HOME}/fio --name=${NAMES[zones - 1]} --filename=/dev/${DEV} --size=100z --ioengine=io_uring --fixedbufs=1 --registerfiles=1 --hipri=1 --sqthread_poll=1 --iodepth=${iodepth} --rw=write --bs=4K --direct=1 --zonemode=zbd --runtime=30s --numjobs=${zones} --offset_increment=100z --max_open_zones=14 --group_reporting --thread=${zones} --ramp_time=10s --output=${DATA_DIR}/${NAMES[zones - 1]}_iodepth-${iodepth}.json --output-format=json --ioscheduler=mq-deadline --time_based
    done
done
